<?php
$arr = [
  'pakai_kacamata' => [
    'blok' => 'radio',
    'label' => 'Apakah Anda memakai kacamata?',
    'value' => $mcu['pakai_kacamata'],
    'required' => 1,
    'value_tidak' => 0,
    'value_ya' => 1,
  ],
  'visus_kanan' => [
    'blok' => 'input-range',
    'label' => 'Visus Mata Kanan: <span class="f20">20/</span>',
    'type' => 'number',
    'placeholder' => '...',
    'value' => $mcu['visus_kanan'],
    'required' => 1,
    'class' => 'mb2 f18 darkblue tengah',
    'min' => 10,
    'max' => 100,
    'minlength' => 0,
    'maxlength' => 0,
    'range' => [20, 25, 30, 35, 40],
    'satuan' => ' '
  ],
  'reflek_cahaya_kanan' => [
    'blok' => 'radio',
    'label' => 'Reflek Cahaya Mata Kanan?',
    'value' => $mcu['reflek_cahaya_kanan'],
    'value_tidak' => '-',
    'value_ya' => '+',
    'label_ya' => 'Positif (+)',
    'label_tidak' => 'Negatif (-)',
  ],
  'konjungtiva_kanan' => [
    'blok' => 'radio',
    'label' => 'konjungtiva Mata Kanan?',
    'value' => $mcu['konjungtiva_kanan'],
    'value_ya' => 'AN',
    'value_tidak' => 'AA',
    'label_ya' => 'Anemis (AN)',
    'label_tidak' => 'An Anemis (AA)',
  ],
  'bola_mata_kanan' => [
    'blok' => 'multi-radio',
    'question' => 'Bentuk Bola Mata Kanan?',
    'value_default' => $mcu['bola_mata_kanan'] ?? '',
    'values' => ['N', 'S', 'L'],
    'labels' => ['Normal', 'Strabismus', 'Lainnya'],
  ],
  'ukuran_pupil_kanan' => [
    'blok' => 'multi-radio',
    'question' => 'Ukuran Pupil Kanan? (mm)',
    'value_default' => $mcu['ukuran_pupil_kanan'] ?? '',
    'values' => [1, 2, 3, 4, 5, 6, 7, 8],
  ],


  'visus_kiri' => [
    'blok' => 'input-range',
    'label' => 'Visus Mata Kiri: <span class="f20">20/</span>',
    'type' => 'number',
    'placeholder' => '...',
    'value' => $mcu['visus_kiri'],
    'required' => 1,
    'class' => 'mb2 f18 darkblue tengah',
    'min' => 10,
    'max' => 100,
    'minlength' => 0,
    'maxlength' => 0,
    'range' => [20, 25, 30, 35, 40],
    'satuan' => ' '
  ],
  'reflek_cahaya_kiri' => [
    'blok' => 'radio',
    'label' => 'Reflek Cahaya Mata Kiri?',
    'value' => $mcu['reflek_cahaya_kiri'],
    'value_tidak' => '-',
    'value_ya' => '+',
    'label_ya' => 'Positif (+)',
    'label_tidak' => 'Negatif (-)',
  ],
  'konjungtiva_kiri' => [
    'blok' => 'radio',
    'label' => 'konjungtiva Mata Kiri?',
    'value' => $mcu['konjungtiva_kiri'],
    'value_ya' => 'AN',
    'value_tidak' => 'AA',
    'label_ya' => 'Anemis (AN)',
    'label_tidak' => 'An Anemis (AA)',
  ],
  'bola_mata_kiri' => [
    'blok' => 'multi-radio',
    'question' => 'Bentuk Bola Mata Kanan?',
    'value_default' => $mcu['bola_mata_kiri'] ?? '',
    'values' => ['N', 'S', 'L'],
    'labels' => ['Normal', 'Strabismus', 'Lainnya'],
  ],
  'ukuran_pupil_kiri' => [
    'blok' => 'multi-radio',
    'question' => 'Ukuran Pupil Kanan? (mm)',
    'value_default' => $mcu['ukuran_pupil_kiri'] ?? '',
    'values' => [1, 2, 3, 4, 5, 6, 7, 8],
  ],

];
