<?php
$arr = [
  'pakai_kacamata' => [
    'blok' => 'radio',
    'label' => 'Apakah Anda memakai kacamata?',
    'value' => $mcu['pakai_kacamata'],
    'required' => 1,
    'value_tidak' => 0,
    'value_ya' => 1,
  ],
  'visus_kanan' => [
    'blok' => 'input-range',
    'label' => 'Visus Mata Kanan: <span class="f20">20/</span>',
    'type' => 'number',
    'placeholder' => '...',
    'value' => $mcu['visus_kanan'],
    'required' => 1,
    'class' => 'mb2 f18 darkblue tengah',
    'min' => 10,
    'max' => 100,
    'minlength' => 0,
    'maxlength' => 0,
    'range' => [20, 25, 30, 35, 40],
    'satuan' => ' '
  ],
  'reflek_cahaya_kanan' => [
    'blok' => 'radio',
    'label' => 'Reflek Cahaya Mata Kanan?',
    'value' => $mcu['reflek_cahaya_kanan'],
    'value_tidak' => '-',
    'value_ya' => '+',
    'label_ya' => 'Positif (+)',
    'label_tidak' => 'Negatif (-)',
  ],
  'konjungtiva_kanan' => [
    'blok' => 'radio',
    'label' => 'konjungtiva Mata Kanan?',
    'value' => $mcu['konjungtiva_kanan'],
    'value_ya' => 'AN',
    'value_tidak' => 'AA',
    'label_ya' => 'Anemis (AN)',
    'label_tidak' => 'An Anemis (AA)',
  ],


  'visus_kiri' => [
    'blok' => 'input-range',
    'label' => 'Visus Mata Kiri: <span class="f20">20/</span>',
    'type' => 'number',
    'placeholder' => '...',
    'value' => $mcu['visus_kiri'],
    'required' => 1,
    'class' => 'mb2 f18 darkblue tengah',
    'min' => 10,
    'max' => 100,
    'minlength' => 0,
    'maxlength' => 0,
    'range' => [20, 25, 30, 35, 40],
    'satuan' => ' '
  ],
  'reflek_cahaya_kiri' => [
    'blok' => 'radio',
    'label' => 'Reflek Cahaya Mata Kiri?',
    'value' => $mcu['reflek_cahaya_kiri'],
    'value_tidak' => '-',
    'value_ya' => '+',
    'label_ya' => 'Positif (+)',
    'label_tidak' => 'Negatif (-)',
  ],
  'konjungtiva_kiri' => [
    'blok' => 'radio',
    'label' => 'konjungtiva Mata Kiri?',
    'value' => $mcu['konjungtiva_kiri'],
    'value_ya' => 'AN',
    'value_tidak' => 'AA',
    'label_ya' => 'Anemis (AN)',
    'label_tidak' => 'An Anemis (AA)',
  ],
];
